name = "Cards Theme"
license = "MIT"
licenselink = "https://github.com/ericgregorich/micro-blog-cards-theme/blob/master/LICENSE"
description = "A simple and lightweight Micro.blog theme based on cards."
homepage = "https://github.com/ericgregorich/micro-blog-cards-theme"
tags = ["theme", "responsive", "simple", "cards", "blog"]
features = ["customizable", "optimized", "SEO"]
min_version = "0.91"
[author]
    name = "Eric Gregorich"
    homepage = "https://ericgregorich.com"
